version: '2.1'
services:
  authority0:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 0
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --ws-interface 0.0.0.0
      --unsafe-expose   
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.10

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.100


  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200
        
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1
